name: fail at pipe

on:
  push:

jobs:
  job:
    runs-on: ubuntu-latest
    steps:
      - name: check
        run: |
          fail | tee log
          echo "${PIPESTATUS[@]}"
          ls ./
          cat log
      - name: second
        run: |
          echo ok
