name: test

on:
  push:
    branches-ignore:
      - "coverage"
  pull_request:
  workflow_dispatch:
    inputs:
      string_var:
        type: string
        description: 'string variable'
        required: false
        default: 'default string'
      choice_var:
        type: choice
        description: 'choice variable'
        required: false
        default: 'b'
        options:
          - 'a'
          - 'b'
          - 'c'
      boolean_var:
        type: boolean
        description: 'boolean variable'
        required: false
        default: false
      environment_var:
        type: environment
        description: 'enviroment variable'
        required: false
        default: hoge
      number_var:
        type: number
        description: 'number variable'
        required: false
        default: 1
      test_type_var:
        type: test_type
        description: 'test_type variable'
        required: false
        default: abc

jobs:
  test:
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment_var }}
    steps:
      - name: inputs check
        run: echo "string_var=${{ inputs.string_var }}, choice_var=${{ inputs.choice_var }}, boolean_var=${{ inputs.boolean_var }}, environment_var=${{ inputs.environment_var }}, number_var=${{ inputs.number_var }}, test_typee_var=${{ inputs.test_type_var }}"
      - name: boolean test
        if: ${{ inputs.boolean_var }}
        run: echo "boolean_var is true"
      - name: string test
        if: ${{ inputs.string_var }}
        run: echo "string_var is true"
      - name: environment test
        run: echo "TEST_VAR=${{ vars.TEST_VAR }}"
